name: PHPUnit
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      env: 
        DEBIAN_FRONTEND: noninteractive
    - name: Prepare Environment
      run: |
        echo "deb http://repo.vitexsoftware.cz $(lsb_release -sc) main backports" | sudo tee /etc/apt/sources.list.d/vitexsoftware.list
        sudo wget -O /etc/apt/trusted.gpg.d/vitexsoftware.gpg http://repo.vitexsoftware.cz/keyring.gpg
        sudo apt-get update
        sudo apt-get install -y composer exim4
        composer update
    - name: Run tests
      run: vendor/bin/phpunit --bootstrap tests/Bootstrap.php --configuration phpunit.xml tests/src/
